language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: UkvY7ck+TIvFstYnrVjGcii6VvnrJLAR5MTUBocqe77zWjiKWloHgczUSAM0LPQ18DVLA7D/TnT97jRKztfiInJYPe7nDPbW0lpc2aBuoLsDQ2QnBXQZ+3YGtetdswbdjLIGV+Jt/2daVEpXKXO2RmRXaSITuGH72Xug8HeSa0+Pimn1+qN3P/zM3x7DWxLPGcx3jqKdl/g3FUXAFK43wghjkCq1Ce7QoDGCDD66NnxUocJ1/KXqPfLwWS9gpR0Nhwj4sUF3gznzPXI2yXQ3VzTK/SNfT9XbnpT0rTqOAys/SKUkY3XTHMnVzOpjvy2/0irvcHmaQZw9r+WBxoTdECq0aaf0jCU+E2HCTNBg2WOeWlLo4GFcBoYzFEFrE0Hz2k0ALB4jttGONAi5UQ2IG1eO4mNiCP886ih7z84E74k6UaRPOsxuO7dsank1XzqiBuBLG/kyC2khV+Y5Q9Y67ae7ynnOCxcSLLTCmP4GxhFzU47m9cN/VaGK6heJrmEVuyvTBFQr9FMd/jXM/VsJ3+vqHiMWaHpZ7esPaD8XXbCcQFnrneMXWf/JWHvsQNalztUE8qk75U7zKwM7uUv0vKpynQWaf0hJK+Lb3HlSriXyQeknU6b0cR8jkIdRLMSJq39XOpMbPdlAtPtfezQJzVGwfhf9OXi2dQ91+rw6z1Q=
  app: finnish-duck
